AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'db/migrate/**'

MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 125

Metrics/AbcSize:
  Max: 21

Metrics/CyclomaticComplexity:
  Max: 8

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
    Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
